using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;

// Responsibility: centralizes player-facing Vanguard Off-Raid strings and locale selection so panels do not embed divergent English/French copies.
// Flow: Canonical API/runtime state is projected into view models and Unity/TMP controls; explicit user actions are delegated back through API/service boundaries.
// Authority boundary: localization changes presentation only and must never encode gameplay state or choose behavioral branches.
// Invariant: every fallback remains readable when the EFT locale cannot be resolved, with English as the stable default.

namespace Vanguard.Client.UI.OffRaid.Localization;

internal enum VanguardPresentationLanguage
{
    English = 0,
    French = 1
}

internal static class VanguardOperatorsLocalizationService
{
    private const string FrenchLocaleCode = "fr";

    private static readonly IReadOnlyDictionary<string, string> EnglishValues = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.button"] = "VANGUARD",
        ["screen.title"] = "VANGUARD OPERATORS",
        ["screen.subtitle"] = "Off-raid operator management · contracts · active service · field hospital · account",
        ["dashboard.contracts"] = "Contracts",
        ["dashboard.active"] = "Active Service",
        ["dashboard.hospital"] = "Field Hospital",
        ["dashboard.billing"] = "Vanguard Account",
        ["action.refresh"] = "Refresh",
        ["action.summary"] = "Summary",
        ["action.back"] = "Back",
        ["action.close"] = "Close",
        ["action.hire"] = "Hire Operator",
        ["action.hire_short"] = "Hire",
        ["action.select"] = "Set Active",
        ["action.unselect"] = "Set Resting",
        ["action.treat"] = "Treat",
        ["action.sign"] = "Sign invoices",
        ["action.dismiss"] = "Release From Service",
        ["action.equipment"] = "Equipment",
        ["action.open_equipment"] = "Open equipment",
        ["action.exit_inventory"] = "Exit inventory",
        ["action.exit_inventory_short"] = "Exit inv.",
        ["action.exit_equipment_session"] = "Exit equipment session",
        ["popup.yes"] = "Confirm",
        ["popup.no"] = "Cancel",
        ["empty.contracts"] = "No contracts available.",
        ["empty.active"] = "No active Operators.",
        ["empty.hospital"] = "No medical records.",
        ["empty.billing"] = "No open invoices.",
        ["general.operator"] = "Operator",
        ["general.unknown_operator"] = "Unknown Operator",
        ["general.none"] = "None",
        ["general.none_fem"] = "None",
        ["general.undefined"] = "Undefined",
        ["general.undefined_fem"] = "Undefined",
        ["general.no_details"] = "No details",
        ["general.available"] = "Available",
        ["general.unavailable"] = "Unavailable",
        ["general.eligible"] = "Eligible",
        ["general.ineligible"] = "Not eligible",
        ["general.blocked"] = "Blocked",
        ["general.active"] = "Active",
        ["general.rest"] = "Resting",
        ["general.stable"] = "Stable",
        ["general.allowed"] = "Allowed",
        ["general.forbidden"] = "Forbidden",
        ["general.medical"] = "MEDICAL",
        ["general.contract"] = "CONTRACT",
        ["general.active_service"] = "ACTIVE SERVICE",
        ["general.hospital"] = "HOSPITAL",
        ["general.offline"] = "OFFLINE",
        ["general.limit_reached"] = "Limit reached",
        ["general.recruitment_limit"] = "Recruitment limit reached",
        ["general.ready"] = "Ready.",
        ["general.session_technical_active"] = "technical session active",
        ["general.equipment_screen_open"] = "equipment screen open",
        ["general.before_raid"] = "exit before raid",
        ["general.action_in_progress"] = "Action in progress · {0}",
        ["general.action_in_progress_named"] = "Action in progress: {0}...",
        ["general.action_failed"] = "Action failed: {0}",
        ["general.state_error"] = "State error: {0}",
        ["general.integrity_ok"] = "Integrity: OK",
        ["general.integrity_warning"] = "Integrity: warning ({0})",
        ["label.level"] = "Level",
        ["label.level_short"] = "Lv.",
        ["label.player_level"] = "Player level",
        ["label.contracts_available"] = "Contracts available",
        ["label.operators_hired"] = "Operators hired",
        ["label.active_service"] = "Active service",
        ["label.raid_active"] = "Selected for next raid",
        ["label.raid_ready"] = "Ready for raid",
        ["label.recovering_operators"] = "Operators recovering",
        ["label.medical_records"] = "Medical records",
        ["label.outstanding_debt"] = "Outstanding debt",
        ["label.operator_identity"] = "Operator identity",
        ["label.portraits"] = "Portraits",
        ["label.actions"] = "Actions",
        ["label.future_inventory"] = "Future inventory",
        ["label.mod_compatibilities"] = "Mod compatibilities",
        ["label.full_inventory"] = "Full inventory",
        ["label.raid_spawn_hud"] = "Raid spawn / HUD",
        ["label.runtime_orchestrator"] = "Runtime orchestrator",
        ["label.ai_image_generation"] = "AI image generation",
        ["label.faction"] = "Faction",
        ["label.role"] = "Role",
        ["label.visual_family"] = "Visual family",
        ["label.contract"] = "Contract",
        ["label.service"] = "Service",
        ["label.service_state"] = "Service state",
        ["label.raid_availability"] = "Raid availability",
        ["label.salary_per_raid"] = "Salary / raid",
        ["label.status"] = "Status",
        ["label.health"] = "Health",
        ["label.recovery"] = "Recovery",
        ["label.injury"] = "Injury",
        ["label.corpses"] = "Corpses",
        ["label.containers"] = "Containers",
        ["label.effective_mode"] = "Effective mode",
        ["label.persona"] = "Persona",
        ["label.doctrine"] = "Doctrine",
        ["label.style"] = "Style",
        ["label.range"] = "Range",
        ["label.squad_role"] = "Squad role",
        ["label.squad_role_short"] = "Squad role",
        ["label.summary"] = "Summary",
        ["label.traits"] = "Traits",
        ["label.progression_level"] = "Level progress (XP within level)",
        ["label.xp_reconciliation"] = "XP reconciliation",
        ["label.raid_xp_acquisition"] = "Raid XP acquisition",
        ["label.raids_survivals_kia"] = "Raids / Survivals / KIA",
        ["label.kills_assists"] = "Kills / Assists",
        ["label.kills"] = "Verified kills (career total)",
        ["label.raid_records"] = "Raid records",
        ["label.latest_raid_recorded"] = "Latest raid recorded",
        ["label.boss_special_targets"] = "Boss / special targets",
        ["label.notable_targets"] = "Notable targets",
        ["label.achievements"] = "Achievements",
        ["label.coverage"] = "Coverage",
        ["label.verified_entries"] = "Verified entries",
        ["label.self_inflicted_kia"] = "Self-inflicted KIA",
        ["label.verified_kills"] = "Verified kills",
        ["label.confirmed_victims"] = "Confirmed victims (career total)",
        ["label.killed_by"] = "Death sources (career total)",
        ["label.cause_how"] = "Cause / how",
        ["label.session_skill_points"] = "Skill points earned (career total)",
        ["label.scope"] = "Scope",
        ["label.reconstructed_raids"] = "Reconstructed raids",
        ["label.aggregate_parity"] = "Verified aggregate parity",
        ["label.display_order"] = "Display order",
        ["label.verified_events"] = "Verified events",
        ["label.terminal_truth"] = "Terminal truth",
        ["label.timestamps"] = "Timestamps",
        ["label.unpersisted_truth"] = "Unpersisted truth",
        ["label.trust_loyalty_respect"] = "Trust / Loyalty / Respect",
        ["label.equipment"] = "Equipment",
        ["label.heal_cost"] = "Treatment cost",
        ["label.acceleration"] = "Acceleration",
        ["label.action"] = "Action",
        ["label.hire_cost"] = "Hire cost",
        ["label.portrait"] = "Portrait",
        ["label.eligibility"] = "Eligibility",
        ["label.flow"] = "Flow",
        ["label.invoices_to_sign"] = "Invoices to sign",
        ["label.signed_auto_archive"] = "Signed / auto archive",
        ["label.paid_history"] = "Paid history",
        ["label.history"] = "History",
        ["label.notifications"] = "NOTIFICATIONS",
        ["label.notification"] = "Notification",
        ["label.total_xp"] = "Total XP (cumulative from level 1)",
        ["label.baseline_xp"] = "Baseline XP (preserved level)",
        ["label.xp_since_enrollment"] = "XP since enrollment",
        ["label.tracked_career_xp"] = "Tracked career XP",
        ["label.xp_since_commit_activation"] = "Career XP since persistent tracking activation",
        ["value.canonical_ui"] = "canonical UI",
        ["value.persistent_test_assets"] = "persistent test assets",
        ["value.confirmation_click_guard"] = "confirmation + double-click guard",
        ["value.not_loaded_model_ready"] = "not loaded / model ready",
        ["value.not_loaded_layer_ready"] = "not loaded / layer ready",
        ["value.out_of_scope"] = "out of scope",
        ["value.pending"] = "Pending",
        ["value.pending_signature"] = "Pending signature",
        ["value.signed_pending_settlement"] = "Signed / auto archive",
        ["value.open"] = "Open",
        ["value.signed"] = "Signed",
        ["value.paid"] = "Paid",
        ["value.hire"] = "Hire",
        ["value.no_response"] = "No response",
        ["value.recovering"] = "Recovering",
        ["value.recovered"] = "Recovered",
        ["value.requires_treatment"] = "Treatment required",
        ["value.selected"] = "Active",
        ["value.selected_for_raid"] = "Active",
        ["value.reserve"] = "Resting",
        ["value.service"] = "Resting",
        ["value.active"] = "Active",
        ["value.available"] = "Available",
        ["value.eligible"] = "Eligible",
        ["value.not_eligible"] = "Not eligible",
        ["value.blocked"] = "Blocked",
        ["value.unavailable"] = "Unavailable",
        ["value.none"] = "None",
        ["value.unknown"] = "Undefined",
        ["value.medical"] = "Medical",
        ["value.recon"] = "Recon",
        ["value.veteran"] = "Veteran",
        ["value.aggressive"] = "Aggressive",
        ["value.calm"] = "Calm",
        ["value.disciplined"] = "Disciplined",
        ["value.methodical"] = "Methodical",
        ["value.patient"] = "Patient",
        ["value.decisive"] = "Decisive",
        ["value.observant"] = "Observant",
        ["value.low_profile"] = "Low profile",
        ["value.controlled_fire"] = "Controlled fire",
        ["value.formation_aware"] = "Formation aware",
        ["value.hardenned"] = "Hardened",
        ["value.hardened"] = "Hardened",
        ["value.survivor"] = "Survivor",
        ["value.recon_overwatch"] = "Recon / overwatch",
        ["value.angle_holder"] = "Angle holder",
        ["value.controlled_push"] = "Controlled push",
        ["value.close_quarters_pressure"] = "CQB pressure",
        ["value.precision_overwatch"] = "Precision overwatch",
        ["role.assault"] = "Assault",
        ["role.breacher"] = "Breacher",
        ["role.pointman"] = "Pointman",
        ["role.marksman"] = "Marksman",
        ["role.support"] = "Support",
        ["role.medic"] = "Medic",
        ["role.scout"] = "Scout",
        ["role.rifleman"] = "Rifleman",
        ["role.operator"] = "Operator",
        ["role.recon"] = "Recon",
        ["role.recon_observation"] = "Recon / observation",
        ["role.recon_overwatch"] = "Recon / overwatch",
        ["role.observation"] = "Observation",
        ["role.assault_pointman"] = "Assault / pointman",
        ["role.room_entry"] = "Room entry",
        ["role.breacher_room_entry"] = "Breacher / entry",
        ["role.precision_overwatch"] = "Precision overwatch",
        ["role.veteran"] = "Veteran",
        ["role.survival"] = "Survival",
        ["role.veteran_survival"] = "Veteran / survival",
        ["range.short"] = "short",
        ["range.medium"] = "medium",
        ["range.long"] = "long",
        ["range.short_medium"] = "short-medium",
        ["range.medium_long"] = "medium-long",
        ["dashboard.body.title"] = "Vanguard operational summary",
        ["dashboard.body.player_level"] = "Player level       : {0} ({1})",
        ["dashboard.body.contracts"] = "Contracts available: {0}",
        ["dashboard.body.operators"] = "Operators hired    : {0} / {1}",
        ["dashboard.body.active_service"] = "Active service     : {0}",
        ["dashboard.body.raid_ready"] = "Ready for raid     : {0}",
        ["dashboard.body.raid_active"] = "Selected next raid : {0} / {1}",
        ["dashboard.body.recovering"] = "Recovering         : {0}",
        ["dashboard.body.medical"] = "Medical records    : {0}",
        ["dashboard.body.debt"] = "Outstanding debt   : {0}",
        ["dashboard.body.note"] = "Persistent Operator readiness, medical state and account status.",
        ["dashboard.title"] = "VANGUARD OPERATIONS",
        ["dashboard.subtitle"] = "Contracts · Active Service · Field Hospital · Account",
        ["dashboard.section.summary"] = "OPERATIONAL SUMMARY",
        ["dashboard.section.foundation"] = "EXTENSIBLE FOUNDATION",
        ["dashboard.section.scope"] = "OFF-RAID SCOPE",
        ["contracts.body.title"] = "Available contracts",
        ["contracts.body.offer_level"] = "  Level {0} · {1} · Hire {2} · Salary {3}/raid",
        ["contracts.body.offer_persona"] = "  Persona {0} · {1} · {2}",
        ["contracts.body.offer_style"] = "  Style {0} · range {1} · squad role {2}",
        ["contracts.body.offer_traits"] = "  Traits {0}",
        ["contracts.limit"] = "Recruitment unavailable: active limit reached for this profile.",
        ["contracts.action.hire_named"] = "Hire {0}",
        ["contracts.title"] = "CONTRACT MARKET",
        ["contracts.subtitle"] = "Hire persistent Vanguard Operators",
        ["service.body.intro"] = "Operators currently attached to Vanguard service.",
        ["service.body.explain"] = "Active = selected for the next raid. Resting = available but not selected.",
        ["service.empty"] = "No Operator in active service.",
        ["service.body.state"] = "  State: {0} · {1} · salary={2}/raid",
        ["service.body.persona"] = "  Persona={0} · doctrine={1}",
        ["service.body.sain"] = "  SAIN={0} · traits={1}",
        ["service.action.rest_named"] = "Set {0} resting",
        ["service.action.active_named"] = "Set {0} active",
        ["service.action.dossier_named"] = "Dossier {0}",
        ["service.title"] = "ACTIVE SERVICE",
        ["service.subtitle"] = "Active Operators are selected for the next raid; Resting Operators remain off duty.",
        ["hospital.body.intro"] = "Persistent medical state and off-raid treatment.",
        ["hospital.empty"] = "No medical record available.",
        ["hospital.body.status"] = "  Status={0} · health={1}% · recovery={2}",
        ["hospital.body.injury"] = "  Injury={0} · treatment={1} · recovery={2}",
        ["hospital.action.treat_named"] = "Treat {0}",
        ["hospital.title"] = "FIELD HOSPITAL",
        ["hospital.subtitle"] = "Off-raid treatment, recovery and deferred billing",
        ["billing.body.intro"] = "Vanguard Account — deferred billing.",
        ["billing.body.flow"] = "The player signs invoices; Vanguard then settles them against the real EFT wallet and archives only confirmed payments.",
        ["billing.body.no_live_debit"] = "Payment uses the real EFT profile economy; a failed or insufficient payment remains pending.",
        ["billing.body.outstanding"] = "Outstanding debt: {0}",
        ["billing.body.to_sign"] = "To sign: {0}",
        ["billing.body.accepted"] = "Signed payments pending settlement: {0}",
        ["billing.title"] = "VANGUARD ACCOUNT",
        ["billing.section.to_sign"] = "INVOICES TO SIGN",
        ["billing.section.accepted"] = "ACCEPTED PAYMENTS",
        ["billing.section.history"] = "PAYMENT HISTORY",
        ["billing.flow.value"] = "Player signature → EFT settlement → paid archive",
        ["billing.empty.pending"] = "No invoice awaiting signature",
        ["billing.auto_archive_refresh"] = "Signed payment awaiting settlement · {0}",
        ["billing.empty.history"] = "No archived payment",
        ["billing.subtitle"] = "Signed invoices, confirmed EFT settlement, readable history.",
        ["billing.action.hint"] = "Signs open invoices and retries any signed payment still pending settlement.",
        ["billing.type.invoice"] = "Invoice",
        ["billing.type.contract_signature"] = "Contract signing",
        ["billing.type.medical_treatment"] = "Medical treatment",
        ["billing.type.raid_salary"] = "Raid salary",
        ["dossier.body.title"] = "Persistent dossier: {0}",
        ["dossier.body.subtitle"] = "Identity, service, career, medical, behavior and relationship summary.",
        ["dossier.section.identity"] = "IDENTITY",
        ["dossier.section.service"] = "SERVICE",
        ["dossier.section.medical"] = "MEDICAL",
        ["dossier.section.loot"] = "OPPORTUNISTIC LOOT",
        ["dossier.section.operational_profile"] = "OPERATIONAL PROFILE",
        ["dossier.section.career"] = "CAREER · CUMULATIVE",
        ["dossier.section.verified_career"] = "CAREER",
        ["dossier.section.raid_history"] = "RAID HISTORY · NEWEST FIRST",
        ["dossier.section.relationship"] = "RELATIONSHIP (UNDER DEVELOPMENT)",
        ["dossier.section.narrative"] = "NARRATIVE",
        ["dossier.title"] = "OPERATOR DOSSIER — {0}",
        ["dossier.subtitle"] = "Persistent identity, career, behavior, relationship and medical summary.",
        ["dossier.action.back_service"] = "Back to active service",
        ["dossier.loot.containers_only"] = "Containers only",
        ["dossier.loot.both"] = "Corpses + containers",
        ["dossier.loot.disabled"] = "Disabled",
        ["dossier.loot.corpses_only"] = "Corpses only",
        ["dossier.behavior"] = "{0} · {1} · range {2} · role {3}",
        ["dossier.reconcile.none"] = "Not required — level and cumulative XP are already coherent on the EFT curve",
        ["dossier.reconcile.reversible"] = "reversible",
        ["dossier.reconcile.irreversible"] = "irreversible",
        ["dossier.reconcile.detail"] = "Reconciliation v{0} — level {1} preserved · previous cumulative XP {2:N0} → {3:N0} (EFT cumulative floor) · {4} · no historical XP invented",
        ["dossier.level_curve.resolve"] = "EFT curve to resolve at runtime",
        ["dossier.level_curve.unavailable"] = "EFT XP curve unavailable — progression not validated",
        ["dossier.level_curve.legacy_unreconciled"] = "Historical profile: cumulative XP not yet reconciled with the preserved level on the EFT curve",
        ["dossier.level_curve.max"] = "Maximum level of the EFT curve",
        ["dossier.level_progress"] = "{0:N0} / {1:N0} XP ({2} %) — next cumulative threshold {3:N0}",
        ["dossier.career.coverage.verified"] = "Verified — supported committed entries only",
        ["dossier.career.coverage.partial_rejected"] = "Partial — {0} rejected entry/entries",
        ["dossier.career.coverage.partial_quarantine"] = "Partial — verified entries, but quarantine history detected",
        ["dossier.career.coverage.no_committed"] = "No committed Career ledger entry",
        ["dossier.career.coverage.no_supported"] = "No verifiable supported entry",
        ["dossier.career.coverage.degraded_unreadable"] = "Degraded — ledger unreadable/quarantined",
        ["dossier.career.coverage.degraded_no_active"] = "Degraded — active ledger absent, quarantine trace present",
        ["dossier.combat_method.not_persisted"] = "Exact cause not recorded for these raids",
        ["dossier.combat_method.unknown"] = "Exact method not determined",
        ["dossier.history.coverage.verified"] = "Verified — committed ledger and aggregate projection agree",
        ["dossier.history.coverage.partial_rejected"] = "Partial — {0} rejected entry/entries",
        ["dossier.history.coverage.partial_quarantine"] = "Partial — quarantine history detected",
        ["dossier.history.coverage.no_committed"] = "No committed raid-ledger entry",
        ["dossier.history.coverage.no_supported"] = "No verifiable supported entry",
        ["dossier.history.coverage.degraded_unreadable"] = "Degraded — ledger unreadable/quarantined",
        ["dossier.history.coverage.degraded_no_active"] = "Degraded — active ledger absent, quarantine trace present",
        ["dossier.parity.unavailable"] = "Unavailable",
        ["dossier.parity.ok"] = "Conformant — {0} Operator(s) compared",
        ["dossier.parity.divergence"] = "DIVERGENCE — {0} difference(s)",
        ["dossier.history.none"] = "No raid history recorded",
        ["dossier.history.last_raid"] = "Last raid",
        ["dossier.history.previous_raid"] = "Previous raid",
        ["dossier.history.older_raid"] = "{0} raids ago",
        ["dossier.history.header_with_time"] = "{0} · recorded {1}",
        ["dossier.history.recorded_at"] = "Recorded {0} (local time)",
        ["dossier.history.timestamp_unavailable"] = "Timestamp unavailable",
        ["dossier.history.victims"] = "Victims",
        ["dossier.history.skills_gained"] = "Skills gained",
        ["dossier.history.notable_event"] = "Notable event",
        ["dossier.history.notable_event_unknown"] = "Recorded event",
        ["dossier.history.raid_label"] = "Raid",
        ["dossier.history.raid_result"] = "{0} · {1} kill(s)",
        ["dossier.history.death_details"] = "Death",
        ["dossier.history.self_inflicted_plain"] = "Self-inflicted",
        ["dossier.history.killed_by_plain"] = "Killed by {0}",
        ["dossier.history.more_label"] = "More",
        ["dossier.history.more_value"] = "+{0} raid(s) recorded",
        ["dossier.history.survival"] = "Survived",
        ["dossier.history.self_inflicted"] = " · Self-inflicted",
        ["dossier.history.killed_by"] = " · Killed by {0}",
        ["dossier.history.entry"] = "{0} · {1} kill(s){2}{3}",
        ["dossier.history.more"] = "{0} | +{1} raid(s)",
        ["dossier.terminal.forward_only"] = "Forward-only — terminal mechanism + last damage zone when observed · last aggressor contextual, never promoted to killer",
        ["dossier.terminal.mechanism"] = " · Terminal: {0}",
        ["dossier.terminal.last_zone"] = " · last zone: {0}",
        ["dossier.terminal.last_aggressor"] = " · Last aggressor: {0} (context, killer not proven)",
        ["dossier.none_verified"] = "None",
        ["dossier.more_others"] = "{0} · +{1} other(s)",
        ["dossier.self_inflicted_count"] = "Self-inflicted{0}",
        ["dossier.skill.none"] = "No verified session point",
        ["dossier.skill.total"] = "{0:0.##} total",
        ["dossier.targets.none"] = "No targeted tracking available",
        ["dossier.targets.no_special"] = "No special target eliminated",
        ["dossier.target"] = "Target",
        ["dossier.achievements.none"] = "No tracked achievement",
        ["dossier.achievements.count"] = "{0} unlocked / {1} tracked",
        ["dossier.eligibility.not_active"] = "Outside active service",
        ["dossier.eligibility.already_deployed"] = "Already deployed",
        ["dossier.eligibility.medical_recovery"] = "Medical recovery active",
        ["dossier.eligibility.low_health"] = "Insufficient health",
        ["dossier.eligibility.unknown"] = "Undetermined",
        ["dossier.xp.tracked_since_activation"] = " (tracked since activation)",
        ["dossier.xp.not_mutated"] = "Not modified — no quantified Vanguard policy is defined",
        ["dossier.xp.commit_pending"] = "Career XP tracking activation pending",
        ["dossier.xp.commit_active"] = "Active — verified EFT kill XP components only (forward-only)",
        ["dossier.xp.commit_active_curve_pending"] = "Active — verified kill XP queued until the authoritative EFT level curve is available",
        ["dossier.career.scope"] = "Committed Career ledger entries only — no implicit historical backfill · self-KIA excluded from kills",
        ["dossier.career.cumulative_scope"] = "Cumulative verified record · {0} recorded raid(s)",
        ["dossier.history.order"] = "Newest first by verified ledger commit time, with deterministic fallbacks",
        ["dossier.history.timestamps"] = "Displayed time is the verified ledger record time in local time — authoritative raid start remains unavailable",
        ["dossier.history.unpersisted"] = "Map · shared authoritative start · Career XP before/after/earned · weapon/ammo · exact causal combat method",
        ["dossier.history.scope"] = "Read-only projection of verified ledger — direct killer=verified terminal event only · last aggressor=contextual · no backfill/streak/Career/XP/Achievement/Persona mutation",
        ["damage.heavy_bleeding"] = "Heavy bleeding",
        ["damage.light_bleeding"] = "Light bleeding",
        ["damage.bullet"] = "Ballistic impact",
        ["damage.explosion"] = "Explosion",
        ["damage.fall"] = "Fall",
        ["damage.barbed"] = "Barbed wire",
        ["damage.dehydration"] = "Dehydration",
        ["damage.exhaustion"] = "Exhaustion",
        ["damage.poison"] = "Poison",
        ["damage.rad_exposure"] = "Radiation",
        ["damage.lethal_toxin"] = "Lethal toxin",
        ["damage.grenade_fragment"] = "Grenade fragment",
        ["damage.landmine"] = "Landmine",
        ["damage.artillery"] = "Artillery",
        ["damage.thermobaric"] = "Thermobaric explosion",
        ["damage.environment"] = "Environment",
        ["body.head"] = "Head",
        ["body.chest"] = "Chest",
        ["body.stomach"] = "Stomach",
        ["body.left_arm"] = "Left arm",
        ["body.right_arm"] = "Right arm",
        ["body.left_leg"] = "Left leg",
        ["body.right_leg"] = "Right leg",
        ["body.common"] = "Body",
        ["combat.guard"] = "Boss guard",
        ["inventory.guard"] = "Operator session active · {0} — return to Main Menu before starting a raid.",
        ["inventory.navigation.blocked"] = "Return to Main Menu to leave the Operator session before opening this section.",
        ["inventory.session_indicator.title"] = "OPERATOR · {0}",
        ["inventory.session_indicator.active"] = "SESSION ACTIVE · MAIN MENU TO EXIT",
        ["inventory.session_indicator.reconciling"] = "RESTORING PLAYER SESSION...",
        ["inventory.status.session"] = "OPERATOR SESSION · {0} · {1} · Main Menu to exit · {2}",
        ["inventory.unavailable"] = "Operator equipment unavailable: menu return still in progress ({0}).",
        ["inventory.confirm.title"] = "Operator Equipment",
        ["inventory.confirm.body"] = "Open {0}'s equipment?\n\nVanguard will start an Operator session that stays active across compatible off-raid menus. Character returns to the Operator inventory; Main Menu saves and restores player state.",
        ["inventory.opening"] = "Opening Operator equipment directly: {0}.",
        ["inventory.opened"] = "Operator session active: {0}. Character returns here; Main Menu saves and exits the session.",
        ["inventory.open_failed_recovered"] = "Unable to open equipment for {0}: {1}. Technical session closed automatically, player inventory restored.",
        ["inventory.enter_failed"] = "Failed to open inventory for {0}: {1}",
        ["inventory.exit_confirm"] = "Save and exit {0}'s equipment session?",
        ["inventory.exit_success"] = "Operator equipment session exited. Player profile preserved.",
        ["inventory.exit_failed"] = "Failed to exit Operator inventory: {0}",
        ["confirm.contract.title"] = "Contract confirmation",
        ["confirm.contract.body"] = "Hire {0}?\nFaction: {1} · Role: {2} · Level: {3}\nHire: {4} · Salary: {5}/raid\nPersona: {6} · Style: {7}",
        ["confirm.service.title"] = "Active service confirmation",
        ["confirm.service.body"] = "Confirm: {0}\n{1}\n\nActive means selected for the next raid; Resting keeps the Operator off duty.",
        ["confirm.service.set_active"] = "set active",
        ["confirm.service.set_rest"] = "set resting",
        ["confirm.treatment.title"] = "Treatment confirmation",
        ["confirm.treatment.body"] = "Treat {0}?\nMedical: {1}\nInjury: {2}\nEstimated deferred cost: {3}",
        ["confirm.billing.title"] = "Invoice confirmation",
        ["confirm.billing.body"] = "Sign open invoices?\nInvoices: {0}\nDebt awaiting signature: {1}",
        ["action.sign_short"] = "Sign",
        ["action.exit"] = "Exit",
        ["status.hire_success"] = "Operator hired: {0}. Invoice created={1}.",
        ["status.hire_failed"] = "Failed to hire {0}: {1}",
        ["status.service_success"] = "Active service updated for {0}: {1}.",
        ["status.service_failed"] = "Failed raid selection for {0}: {1}",
        ["status.loot_success"] = "Opportunistic loot updated for {0}: {1}.",
        ["status.loot_failed"] = "Failed to update opportunistic loot: {0}",
        ["status.treatment_success"] = "Treatment completed: {0}; health {1:P0} → {2:P0}; amount={3}.",
        ["status.treatment_failed"] = "Treatment failed for {0}: {1}",
        ["status.billing_success"] = "Invoices signed: {0}; amount={1}. Automatic archive on refresh.",
        ["status.billing_failed"] = "Signature failed: {0}",
        ["tooltip.identity"] = "IDENTITY",
        ["tooltip.operational_profile"] = "OPERATIONAL PROFILE",
        ["tooltip.level_line"] = "{0} · {1} · Level {2} · {3}",
        ["tooltip.row"] = "{0}: {1}",
        ["combatant.scav"] = "Scav",
        ["combatant.scav_sniper"] = "Scav sniper",
        ["combatant.boss"] = "Boss",
        ["general.inventory_active"] = "Inventory active",
        ["general.confirmation_required"] = "Confirmation required",
        ["general.adaptive_style"] = "Adaptive style",
        ["general.unknown_raid"] = "unknown-raid",
        ["billing.notification.debt_added_title"] = "Vanguard invoice created",
        ["billing.notification.debt_added_message"] = "Deferred debt added · {0}",
    };

    private static readonly IReadOnlyDictionary<string, string> FrenchValues = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.button"] = "VANGUARD",
        ["screen.title"] = "OPÉRATEURS VANGUARD",
        ["screen.subtitle"] = "Gestion hors raid des opérateurs · contrats · service actif · hôpital de campagne · compte",
        ["dashboard.contracts"] = "Contrats",
        ["dashboard.active"] = "Service actif",
        ["dashboard.hospital"] = "Hôpital de campagne",
        ["dashboard.billing"] = "Compte Vanguard",
        ["action.refresh"] = "Actualiser",
        ["action.summary"] = "Synthèse",
        ["action.back"] = "Retour",
        ["action.close"] = "Fermer",
        ["action.hire"] = "Recruter l'opérateur",
        ["action.hire_short"] = "Engager",
        ["action.select"] = "Mettre actif",
        ["action.unselect"] = "Mettre au repos",
        ["action.treat"] = "Traiter",
        ["action.sign"] = "Signer les factures",
        ["action.dismiss"] = "Libérer du service",
        ["action.equipment"] = "Équipement",
        ["action.open_equipment"] = "Ouvrir équipement",
        ["action.exit_inventory"] = "Quitter inventaire",
        ["action.exit_inventory_short"] = "Quitter inv.",
        ["action.exit_equipment_session"] = "Quitter session équipement",
        ["popup.yes"] = "Confirmer",
        ["popup.no"] = "Annuler",
        ["empty.contracts"] = "Aucun contrat disponible.",
        ["empty.active"] = "Aucun opérateur actif.",
        ["empty.hospital"] = "Aucun dossier médical.",
        ["empty.billing"] = "Aucune facture en attente.",
        ["general.operator"] = "Operator",
        ["general.unknown_operator"] = "Operator inconnu",
        ["general.none"] = "Aucun",
        ["general.none_fem"] = "Aucune",
        ["general.undefined"] = "Non défini",
        ["general.undefined_fem"] = "Non définie",
        ["general.no_details"] = "Aucun détail",
        ["general.available"] = "Disponible",
        ["general.unavailable"] = "Indisponible",
        ["general.eligible"] = "Éligible",
        ["general.ineligible"] = "Non éligible",
        ["general.blocked"] = "Bloqué",
        ["general.active"] = "Actif",
        ["general.rest"] = "Repos",
        ["general.stable"] = "Stable",
        ["general.allowed"] = "Autorisé",
        ["general.forbidden"] = "Interdit",
        ["general.medical"] = "MÉDICAL",
        ["general.contract"] = "CONTRAT",
        ["general.active_service"] = "SERVICE ACTIF",
        ["general.hospital"] = "HÔPITAL",
        ["general.offline"] = "HORS LIGNE",
        ["general.limit_reached"] = "Limite atteinte",
        ["general.recruitment_limit"] = "Limite de recrutement atteinte",
        ["general.ready"] = "Prêt.",
        ["general.session_technical_active"] = "session technique active",
        ["general.equipment_screen_open"] = "écran équipement ouvert",
        ["general.before_raid"] = "quitter avant raid",
        ["general.action_in_progress"] = "Action en cours · {0}",
        ["general.action_in_progress_named"] = "Action en cours : {0}...",
        ["general.action_failed"] = "Action échouée : {0}",
        ["general.state_error"] = "Erreur état : {0}",
        ["general.integrity_ok"] = "Intégrité: OK",
        ["general.integrity_warning"] = "Intégrité: attention ({0})",
        ["label.level"] = "Niveau",
        ["label.level_short"] = "Niv.",
        ["label.player_level"] = "Niveau joueur",
        ["label.contracts_available"] = "Contrats disponibles",
        ["label.operators_hired"] = "Operators engagés",
        ["label.active_service"] = "Service actif",
        ["label.raid_active"] = "Sélectionnés prochain raid",
        ["label.raid_ready"] = "Prêts pour le raid",
        ["label.recovering_operators"] = "Operators en récupération",
        ["label.medical_records"] = "Dossiers médicaux",
        ["label.outstanding_debt"] = "Dette ouverte",
        ["label.operator_identity"] = "Identité Operator",
        ["label.portraits"] = "Portraits",
        ["label.actions"] = "Actions",
        ["label.future_inventory"] = "Inventaire futur",
        ["label.mod_compatibilities"] = "Compatibilités mods",
        ["label.full_inventory"] = "Inventaire complet",
        ["label.raid_spawn_hud"] = "Spawn / HUD raid",
        ["label.runtime_orchestrator"] = "Orchestrator runtime",
        ["label.ai_image_generation"] = "Génération IA images",
        ["label.faction"] = "Faction",
        ["label.role"] = "Rôle",
        ["label.visual_family"] = "Famille visuelle",
        ["label.contract"] = "Contrat",
        ["label.service"] = "Service",
        ["label.service_state"] = "État service",
        ["label.raid_availability"] = "Disponibilité raid",
        ["label.salary_per_raid"] = "Salaire / raid",
        ["label.status"] = "Statut",
        ["label.health"] = "Santé",
        ["label.recovery"] = "Récupération",
        ["label.injury"] = "Blessure",
        ["label.corpses"] = "Cadavres",
        ["label.containers"] = "Conteneurs",
        ["label.effective_mode"] = "Mode effectif",
        ["label.persona"] = "Persona",
        ["label.doctrine"] = "Doctrine",
        ["label.style"] = "Style",
        ["label.range"] = "Portée",
        ["label.squad_role"] = "Rôle escouade",
        ["label.squad_role_short"] = "Rôle squad",
        ["label.summary"] = "Synthèse",
        ["label.traits"] = "Traits",
        ["label.progression_level"] = "Progression du niveau (XP du niveau)",
        ["label.xp_reconciliation"] = "Réconciliation XP",
        ["label.raid_xp_acquisition"] = "Acquisition XP raid",
        ["label.raids_survivals_kia"] = "Raids / Survies / KIA",
        ["label.kills_assists"] = "Kills / Assists",
        ["label.kills"] = "Kills vérifiés (cumul carrière)",
        ["label.raid_records"] = "Raids enregistrés",
        ["label.latest_raid_recorded"] = "Dernier raid enregistré",
        ["label.boss_special_targets"] = "Boss / cibles spéciales",
        ["label.notable_targets"] = "Cibles notables",
        ["label.achievements"] = "Hauts faits",
        ["label.coverage"] = "Couverture",
        ["label.verified_entries"] = "Entrées vérifiées",
        ["label.self_inflicted_kia"] = "KIA auto-infligées",
        ["label.verified_kills"] = "Kills vérifiés",
        ["label.confirmed_victims"] = "Victimes confirmées (cumul carrière)",
        ["label.killed_by"] = "Sources de décès (cumul carrière)",
        ["label.cause_how"] = "Cause / comment",
        ["label.session_skill_points"] = "Points de compétence gagnés (cumul carrière)",
        ["label.scope"] = "Périmètre",
        ["label.reconstructed_raids"] = "Raids reconstruits",
        ["label.aggregate_parity"] = "Parité des agrégats vérifiés",
        ["label.display_order"] = "Ordre d'affichage",
        ["label.verified_events"] = "Évènements vérifiés",
        ["label.terminal_truth"] = "Vérité terminale",
        ["label.timestamps"] = "Timestamps",
        ["label.unpersisted_truth"] = "Vérités non persistées",
        ["label.trust_loyalty_respect"] = "Trust / Loyalty / Respect",
        ["label.equipment"] = "Équipement",
        ["label.heal_cost"] = "Coût soin",
        ["label.acceleration"] = "Accélération",
        ["label.action"] = "Action",
        ["label.hire_cost"] = "Engagement",
        ["label.portrait"] = "Portrait",
        ["label.eligibility"] = "Éligibilité",
        ["label.flow"] = "Flux",
        ["label.invoices_to_sign"] = "Factures à signer",
        ["label.signed_auto_archive"] = "Signées / archivage auto",
        ["label.paid_history"] = "Historique payé",
        ["label.history"] = "Historique",
        ["label.notifications"] = "NOTIFICATIONS",
        ["label.notification"] = "Notification",
        ["label.total_xp"] = "XP totale (cumulée depuis le niveau 1)",
        ["label.baseline_xp"] = "XP baseline (niveau préservé)",
        ["label.xp_since_enrollment"] = "XP depuis enrôlement",
        ["label.tracked_career_xp"] = "XP carrière suivie",
        ["label.xp_since_commit_activation"] = "XP carrière depuis l’activation du suivi persistant",
        ["value.canonical_ui"] = "canonique UI",
        ["value.persistent_test_assets"] = "assets test persistants",
        ["value.confirmation_click_guard"] = "confirmation + verrou anti double-clic",
        ["value.not_loaded_model_ready"] = "non chargé / modèle préparé",
        ["value.not_loaded_layer_ready"] = "non chargées / couche préparée",
        ["value.out_of_scope"] = "hors périmètre",
        ["value.pending"] = "En attente",
        ["value.pending_signature"] = "À signer",
        ["value.signed_pending_settlement"] = "Signée / archivage auto",
        ["value.open"] = "Ouverte",
        ["value.signed"] = "Signée",
        ["value.paid"] = "Payée",
        ["value.hire"] = "Engagement",
        ["value.no_response"] = "Pas de réponse",
        ["value.recovering"] = "En récupération",
        ["value.recovered"] = "Récupéré",
        ["value.requires_treatment"] = "Soin requis",
        ["value.selected"] = "Actif",
        ["value.selected_for_raid"] = "Actif",
        ["value.reserve"] = "Repos",
        ["value.service"] = "Repos",
        ["value.active"] = "Actif",
        ["value.available"] = "Disponible",
        ["value.eligible"] = "Éligible",
        ["value.not_eligible"] = "Non éligible",
        ["value.blocked"] = "Bloqué",
        ["value.unavailable"] = "Indisponible",
        ["value.none"] = "Aucun",
        ["value.unknown"] = "Non défini",
        ["value.medical"] = "Médical",
        ["value.recon"] = "Recon",
        ["value.veteran"] = "Vétéran",
        ["value.aggressive"] = "Agressif",
        ["value.calm"] = "Calme",
        ["value.disciplined"] = "Discipliné",
        ["value.methodical"] = "Méthodique",
        ["value.patient"] = "Patient",
        ["value.decisive"] = "Décisif",
        ["value.observant"] = "Observateur",
        ["value.low_profile"] = "Profil discret",
        ["value.controlled_fire"] = "Tir contrôlé",
        ["value.formation_aware"] = "Cohésion formation",
        ["value.hardenned"] = "Aguerri",
        ["value.hardened"] = "Aguerri",
        ["value.survivor"] = "Survivant",
        ["value.recon_overwatch"] = "Recon / surveillance",
        ["value.angle_holder"] = "Tenue d’angle",
        ["value.controlled_push"] = "Progression contrôlée",
        ["value.close_quarters_pressure"] = "Pression CQB",
        ["value.precision_overwatch"] = "Surveillance précision",
        ["role.assault"] = "Assaut",
        ["role.breacher"] = "Brèche",
        ["role.pointman"] = "Ouvreur",
        ["role.marksman"] = "Tireur précision",
        ["role.support"] = "Support",
        ["role.medic"] = "Médecin",
        ["role.scout"] = "Éclaireur",
        ["role.rifleman"] = "Fusilier",
        ["role.operator"] = "Operator",
        ["role.recon"] = "Recon",
        ["role.recon_observation"] = "Recon / observation",
        ["role.recon_overwatch"] = "Recon / surveillance",
        ["role.observation"] = "Observation",
        ["role.assault_pointman"] = "Assaut / ouvreur",
        ["role.room_entry"] = "Entrée de pièce",
        ["role.breacher_room_entry"] = "Brèche / entrée",
        ["role.precision_overwatch"] = "Surveillance précision",
        ["role.veteran"] = "Vétéran",
        ["role.survival"] = "Survie",
        ["role.veteran_survival"] = "Vétéran / survie",
        ["range.short"] = "courte",
        ["range.medium"] = "moyenne",
        ["range.long"] = "longue",
        ["range.short_medium"] = "courte-moyenne",
        ["range.medium_long"] = "moyenne-longue",
        ["dashboard.body.title"] = "Synthèse opérationnelle Vanguard",
        ["dashboard.body.player_level"] = "Niveau joueur       : {0} ({1})",
        ["dashboard.body.contracts"] = "Contrats disponibles: {0}",
        ["dashboard.body.operators"] = "Operators engagés   : {0} / {1}",
        ["dashboard.body.active_service"] = "Service actif       : {0}",
        ["dashboard.body.raid_ready"] = "Prêts pour le raid  : {0}",
        ["dashboard.body.raid_active"] = "Prochain raid       : {0} / {1}",
        ["dashboard.body.recovering"] = "En récupération     : {0}",
        ["dashboard.body.medical"] = "Dossiers médicaux   : {0}",
        ["dashboard.body.debt"] = "Dette ouverte       : {0}",
        ["dashboard.body.note"] = "Disponibilité persistante des Operators, état médical et situation du compte.",
        ["dashboard.title"] = "OPÉRATIONS VANGUARD",
        ["dashboard.subtitle"] = "Contrats · Service actif · Hôpital de campagne · Compte",
        ["dashboard.section.summary"] = "SYNTHÈSE OPÉRATIONNELLE",
        ["dashboard.section.foundation"] = "FONDATION EXTENSIBLE",
        ["dashboard.section.scope"] = "PÉRIMÈTRE HORS RAID",
        ["contracts.body.title"] = "Contrats disponibles",
        ["contracts.body.offer_level"] = "  Level {0} · {1} · Hire {2} · Salary {3}/raid",
        ["contracts.body.offer_persona"] = "  Persona {0} · {1} · {2}",
        ["contracts.body.offer_style"] = "  Style {0} · portée {1} · rôle escouade {2}",
        ["contracts.body.offer_traits"] = "  Traits {0}",
        ["contracts.limit"] = "Recrutement indisponible : limite active atteinte pour ce profil.",
        ["contracts.action.hire_named"] = "Engager {0}",
        ["contracts.title"] = "MARCHÉ DES CONTRATS",
        ["contracts.subtitle"] = "Recruter des Operators Vanguard persistants",
        ["service.body.intro"] = "Operators actuellement rattachés au service Vanguard.",
        ["service.body.explain"] = "État Actif = sélectionné pour le prochain raid. Repos = disponible mais non sélectionné.",
        ["service.empty"] = "Aucun Operator en service actif.",
        ["service.body.state"] = "  État: {0} · {1} · salaire={2}/raid",
        ["service.body.persona"] = "  Persona={0} · doctrine={1}",
        ["service.body.sain"] = "  SAIN={0} · traits={1}",
        ["service.action.rest_named"] = "Mettre au repos {0}",
        ["service.action.active_named"] = "Mettre actif {0}",
        ["service.action.dossier_named"] = "Dossier {0}",
        ["service.title"] = "SERVICE ACTIF",
        ["service.subtitle"] = "Les Operators actifs sont sélectionnés pour le prochain raid ; les Operators au repos restent hors service.",
        ["hospital.body.intro"] = "État médical persistant et soins hors raid.",
        ["hospital.empty"] = "Aucun dossier médical disponible.",
        ["hospital.body.status"] = "  Statut={0} · santé={1}% · récupération={2}",
        ["hospital.body.injury"] = "  Blessure={0} · soin={1} · récupération={2}",
        ["hospital.action.treat_named"] = "Traiter {0}",
        ["hospital.title"] = "HÔPITAL DE CAMPAGNE",
        ["hospital.subtitle"] = "Soins hors raid, récupération et facturation différée",
        ["billing.body.intro"] = "Compte Vanguard — facturation différée.",
        ["billing.body.flow"] = "Le joueur signe les factures ; Vanguard les règle ensuite sur le portefeuille EFT réel et n’archive que les paiements confirmés.",
        ["billing.body.no_live_debit"] = "Le paiement utilise l’économie réelle du profil EFT ; un paiement refusé ou insuffisant reste en attente.",
        ["billing.body.outstanding"] = "Dette ouverte : {0}",
        ["billing.body.to_sign"] = "À signer : {0}",
        ["billing.body.accepted"] = "Paiements signés en attente de règlement : {0}",
        ["billing.title"] = "COMPTE VANGUARD",
        ["billing.section.to_sign"] = "FACTURES À SIGNER",
        ["billing.section.accepted"] = "PAIEMENTS ACCEPTÉS",
        ["billing.section.history"] = "HISTORIQUE DES PAIEMENTS",
        ["billing.flow.value"] = "Signature joueur → règlement EFT → archivage payé",
        ["billing.empty.pending"] = "Aucune facture en attente de signature",
        ["billing.auto_archive_refresh"] = "Paiement signé en attente de règlement · {0}",
        ["billing.empty.history"] = "Aucun paiement archivé",
        ["billing.subtitle"] = "Factures signées, règlement EFT confirmé, historique lisible.",
        ["billing.action.hint"] = "Signe les factures ouvertes et retente tout paiement signé encore en attente de règlement.",
        ["billing.type.invoice"] = "Facture",
        ["billing.type.contract_signature"] = "Signature de contrat",
        ["billing.type.medical_treatment"] = "Soins médicaux",
        ["billing.type.raid_salary"] = "Salaire de raid",
        ["dossier.body.title"] = "Dossier persistant : {0}",
        ["dossier.body.subtitle"] = "Synthèse identité, service, carrière, médical, comportement et relation.",
        ["dossier.section.identity"] = "IDENTITÉ",
        ["dossier.section.service"] = "SERVICE",
        ["dossier.section.medical"] = "MÉDICAL",
        ["dossier.section.loot"] = "LOOT OPPORTUNISTE",
        ["dossier.section.operational_profile"] = "PROFIL OPÉRATIONNEL",
        ["dossier.section.career"] = "CARRIÈRE · CUMULÉ",
        ["dossier.section.verified_career"] = "CARRIÈRE",
        ["dossier.section.raid_history"] = "HISTORIQUE DES RAIDS · PLUS RÉCENTS D’ABORD",
        ["dossier.section.relationship"] = "RELATION (EN DÉVELOPPEMENT)",
        ["dossier.section.narrative"] = "NARRATIF",
        ["dossier.title"] = "DOSSIER OPERATOR — {0}",
        ["dossier.subtitle"] = "Identité persistante, carrière, comportement, relation et résumé médical.",
        ["dossier.action.back_service"] = "Retour service actif",
        ["dossier.loot.containers_only"] = "Conteneurs uniquement",
        ["dossier.loot.both"] = "Cadavres + conteneurs",
        ["dossier.loot.disabled"] = "Désactivé",
        ["dossier.loot.corpses_only"] = "Cadavres uniquement",
        ["dossier.behavior"] = "{0} · {1} · portée {2} · rôle {3}",
        ["dossier.reconcile.none"] = "Non requise — niveau et XP cumulée déjà cohérents sur la courbe EFT",
        ["dossier.reconcile.reversible"] = "réversible",
        ["dossier.reconcile.irreversible"] = "non réversible",
        ["dossier.reconcile.detail"] = "Réconciliation v{0} — niveau {1} préservé · XP cumulée précédente {2:N0} → {3:N0} (plancher EFT cumulatif) · {4} · aucune XP historique inventée",
        ["dossier.level_curve.resolve"] = "Courbe EFT à résoudre au runtime",
        ["dossier.level_curve.unavailable"] = "Courbe XP EFT indisponible — progression non validée",
        ["dossier.level_curve.legacy_unreconciled"] = "Profil historique : XP cumulée non encore réconciliée avec le niveau préservé sur la courbe EFT",
        ["dossier.level_curve.max"] = "Niveau maximum de la courbe EFT",
        ["dossier.level_progress"] = "{0:N0} / {1:N0} XP ({2} %) — prochain seuil cumulatif {3:N0}",
        ["dossier.career.coverage.verified"] = "Vérifiée — entrées commitées supportées uniquement",
        ["dossier.career.coverage.partial_rejected"] = "Partielle — {0} entrée(s) rejetée(s)",
        ["dossier.career.coverage.partial_quarantine"] = "Partielle — entrées vérifiées, mais historique de quarantaine détecté",
        ["dossier.career.coverage.no_committed"] = "Aucune entrée Career commitée dans le ledger",
        ["dossier.career.coverage.no_supported"] = "Aucune entrée supportée vérifiable",
        ["dossier.career.coverage.degraded_unreadable"] = "Dégradée — ledger illisible/quarantiné",
        ["dossier.career.coverage.degraded_no_active"] = "Dégradée — ledger actif absent, trace de quarantaine présente",
        ["dossier.combat_method.not_persisted"] = "Cause exacte non enregistrée pour ces raids",
        ["dossier.combat_method.unknown"] = "Moyen exact non déterminé",
        ["dossier.history.coverage.verified"] = "Vérifiée — le ledger commité et la projection agrégée concordent",
        ["dossier.history.coverage.partial_rejected"] = "Partielle — {0} entrée(s) rejetée(s)",
        ["dossier.history.coverage.partial_quarantine"] = "Partielle — historique de quarantaine détecté",
        ["dossier.history.coverage.no_committed"] = "Aucune entrée de ledger de raid commitée",
        ["dossier.history.coverage.no_supported"] = "Aucune entrée supportée vérifiable",
        ["dossier.history.coverage.degraded_unreadable"] = "Dégradée — ledger illisible/quarantiné",
        ["dossier.history.coverage.degraded_no_active"] = "Dégradée — ledger actif absent, trace de quarantaine présente",
        ["dossier.parity.unavailable"] = "Non disponible",
        ["dossier.parity.ok"] = "Conforme — {0} Operator(s) comparé(s)",
        ["dossier.parity.divergence"] = "DIVERGENCE — {0} écart(s)",
        ["dossier.history.none"] = "Aucun historique de raid enregistré",
        ["dossier.history.last_raid"] = "Dernier raid",
        ["dossier.history.previous_raid"] = "Raid précédent",
        ["dossier.history.older_raid"] = "{0} raids plus tôt",
        ["dossier.history.header_with_time"] = "{0} · enregistré {1}",
        ["dossier.history.recorded_at"] = "Enregistré le {0} (heure locale)",
        ["dossier.history.timestamp_unavailable"] = "Horodatage indisponible",
        ["dossier.history.victims"] = "Victimes",
        ["dossier.history.skills_gained"] = "Compétences gagnées",
        ["dossier.history.notable_event"] = "Évènement notable",
        ["dossier.history.notable_event_unknown"] = "Évènement enregistré",
        ["dossier.history.raid_label"] = "Raid",
        ["dossier.history.raid_result"] = "{0} · {1} kill(s)",
        ["dossier.history.death_details"] = "Mort",
        ["dossier.history.self_inflicted_plain"] = "Auto-infligée",
        ["dossier.history.killed_by_plain"] = "Tué par {0}",
        ["dossier.history.more_label"] = "Autres",
        ["dossier.history.more_value"] = "+{0} raid(s) enregistré(s)",
        ["dossier.history.survival"] = "Survie",
        ["dossier.history.self_inflicted"] = " · Auto-infligée",
        ["dossier.history.killed_by"] = " · Tué par {0}",
        ["dossier.history.entry"] = "{0} · {1} kill(s){2}{3}",
        ["dossier.history.more"] = "{0} | +{1} raid(s)",
        ["dossier.terminal.forward_only"] = "Forward-only — mécanisme terminal + dernière zone de dommage si observés · dernier agresseur contextuel, jamais promu en killer",
        ["dossier.terminal.mechanism"] = " · Terminal: {0}",
        ["dossier.terminal.last_zone"] = " · dernière zone: {0}",
        ["dossier.terminal.last_aggressor"] = " · Dernier agresseur: {0} (contexte, killer non prouvé)",
        ["dossier.none_verified"] = "Aucune",
        ["dossier.more_others"] = "{0} · +{1} autre(s)",
        ["dossier.self_inflicted_count"] = "Auto-infligée{0}",
        ["dossier.skill.none"] = "Aucun point session vérifié",
        ["dossier.skill.total"] = "{0:0.##} total",
        ["dossier.targets.none"] = "Aucun suivi ciblé disponible",
        ["dossier.targets.no_special"] = "Aucune cible spéciale éliminée",
        ["dossier.target"] = "Cible",
        ["dossier.achievements.none"] = "Aucun haut fait suivi",
        ["dossier.achievements.count"] = "{0} débloqué(s) / {1} suivi(s)",
        ["dossier.eligibility.not_active"] = "Hors service actif",
        ["dossier.eligibility.already_deployed"] = "Déjà déployé",
        ["dossier.eligibility.medical_recovery"] = "En récupération médicale",
        ["dossier.eligibility.low_health"] = "Santé insuffisante",
        ["dossier.eligibility.unknown"] = "Non déterminée",
        ["dossier.xp.tracked_since_activation"] = " (suivi depuis activation)",
        ["dossier.xp.not_mutated"] = "Non modifiée — aucune politique Vanguard chiffrée n'est définie",
        ["dossier.xp.commit_pending"] = "Activation du suivi XP carrière en attente",
        ["dossier.xp.commit_active"] = "Active — composantes XP de kill EFT vérifiées uniquement (sans rétroactivité)",
        ["dossier.xp.commit_active_curve_pending"] = "Active — XP de kill vérifiée en attente de la courbe de niveau EFT autoritaire",
        ["dossier.career.scope"] = "Entrées Career commitées du ledger uniquement — aucun backfill historique implicite · auto-KIA exclues des kills",
        ["dossier.career.cumulative_scope"] = "Dossier vérifié cumulé · {0} raid(s) enregistré(s)",
        ["dossier.history.order"] = "Du plus récent au plus ancien selon l’heure de commit vérifiée du ledger, avec replis déterministes",
        ["dossier.history.timestamps"] = "L’heure affichée est l’heure locale d’enregistrement vérifiée du ledger — le début autoritaire du raid reste indisponible",
        ["dossier.history.unpersisted"] = "Map · début autoritaire commun · XP Career avant/après/gagnée · arme/munition · méthode de combat causale exacte",
        ["dossier.history.scope"] = "Projection read-only du ledger vérifié — killer direct=événement terminal vérifié uniquement · dernier agresseur=contextuel · aucun backfill/streak/mutation Career/XP/Achievement/Persona",
        ["damage.heavy_bleeding"] = "Hémorragie lourde",
        ["damage.light_bleeding"] = "Hémorragie légère",
        ["damage.bullet"] = "Impact balistique",
        ["damage.explosion"] = "Explosion",
        ["damage.fall"] = "Chute",
        ["damage.barbed"] = "Barbelés",
        ["damage.dehydration"] = "Déshydratation",
        ["damage.exhaustion"] = "Épuisement",
        ["damage.poison"] = "Poison",
        ["damage.rad_exposure"] = "Radiation",
        ["damage.lethal_toxin"] = "Toxine létale",
        ["damage.grenade_fragment"] = "Fragment de grenade",
        ["damage.landmine"] = "Mine",
        ["damage.artillery"] = "Artillerie",
        ["damage.thermobaric"] = "Explosion thermobarique",
        ["damage.environment"] = "Environnement",
        ["body.head"] = "Tête",
        ["body.chest"] = "Thorax",
        ["body.stomach"] = "Ventre",
        ["body.left_arm"] = "Bras gauche",
        ["body.right_arm"] = "Bras droit",
        ["body.left_leg"] = "Jambe gauche",
        ["body.right_leg"] = "Jambe droite",
        ["body.common"] = "Corps",
        ["combat.guard"] = "Garde de boss",
        ["inventory.guard"] = "Session Operator active · {0} — revenez au menu principal avant de lancer un raid.",
        ["inventory.navigation.blocked"] = "Revenez au menu principal pour quitter la session Operator avant d’ouvrir cette section.",
        ["inventory.session_indicator.title"] = "OPERATOR · {0}",
        ["inventory.session_indicator.active"] = "SESSION ACTIVE · MENU PRINCIPAL POUR QUITTER",
        ["inventory.session_indicator.reconciling"] = "RESTAURATION DE LA SESSION JOUEUR...",
        ["inventory.status.session"] = "SESSION OPERATOR · {0} · {1} · menu principal pour quitter · {2}",
        ["inventory.unavailable"] = "Équipement Operator indisponible : retour menu encore en cours ({0}).",
        ["inventory.confirm.title"] = "Équipement Operator",
        ["inventory.confirm.body"] = "Ouvrir l’équipement de {0}?\n\nVanguard ouvre une session Operator qui reste active dans les menus hors raid compatibles. Character revient à l’inventaire Operator ; le menu principal sauvegarde et restaure l’état joueur.",
        ["inventory.opening"] = "Ouverture directe de l’équipement Operator : {0}.",
        ["inventory.opened"] = "Session Operator active : {0}. Character revient ici ; le menu principal sauvegarde et quitte la session.",
        ["inventory.open_failed_recovered"] = "Ouverture équipement impossible pour {0}: {1}. Session technique fermée automatiquement, inventaire joueur restauré.",
        ["inventory.enter_failed"] = "Échec ouverture inventaire pour {0}: {1}",
        ["inventory.exit_confirm"] = "Sauvegarder et quitter la session équipement de {0}?",
        ["inventory.exit_success"] = "Session équipement Operator quittée. Profil joueur conservé.",
        ["inventory.exit_failed"] = "Échec sortie inventaire Operator: {0}",
        ["confirm.contract.title"] = "Confirmation contrat",
        ["confirm.contract.body"] = "Engager {0}?\nFaction: {1} · Rôle: {2} · Niveau: {3}\nEngagement: {4} · Salaire: {5}/raid\nPersona: {6} · Style: {7}",
        ["confirm.service.title"] = "Confirmation service actif",
        ["confirm.service.body"] = "Confirmer : {0}\n{1}\n\nActif signifie sélectionné pour le prochain raid ; Repos maintient l’Operator hors service.",
        ["confirm.service.set_active"] = "mettre actif",
        ["confirm.service.set_rest"] = "mettre au repos",
        ["confirm.treatment.title"] = "Confirmation soin",
        ["confirm.treatment.body"] = "Traiter {0}?\nMédical: {1}\nBlessure: {2}\nCoût différé estimé: {3}",
        ["confirm.billing.title"] = "Confirmation factures",
        ["confirm.billing.body"] = "Signer les factures ouvertes?\nFactures: {0}\nDette en attente de signature: {1}",
        ["action.sign_short"] = "Signer",
        ["action.exit"] = "Quitter",
        ["status.hire_success"] = "Operator engagé : {0}. Facture créée={1}.",
        ["status.hire_failed"] = "Échec engagement {0}: {1}",
        ["status.service_success"] = "Service actif mis à jour pour {0}: {1}.",
        ["status.service_failed"] = "Échec sélection raid pour {0}: {1}",
        ["status.loot_success"] = "Loot opportuniste mis à jour pour {0} : {1}.",
        ["status.loot_failed"] = "Échec mise à jour loot opportuniste : {0}",
        ["status.treatment_success"] = "Soin effectué : {0}; santé {1:P0} → {2:P0}; montant={3}.",
        ["status.treatment_failed"] = "Échec soin pour {0}: {1}",
        ["status.billing_success"] = "Factures signées : {0}; montant={1}. Archivage automatique au refresh.",
        ["status.billing_failed"] = "Échec signature : {0}",
        ["tooltip.identity"] = "IDENTITÉ",
        ["tooltip.operational_profile"] = "PROFIL OPÉRATIONNEL",
        ["tooltip.level_line"] = "{0} · {1} · Niveau {2} · {3}",
        ["tooltip.row"] = "{0}: {1}",
        ["combatant.scav"] = "Scav",
        ["combatant.scav_sniper"] = "Scav sniper",
        ["combatant.boss"] = "Boss",
        ["general.inventory_active"] = "Inventaire actif",
        ["general.confirmation_required"] = "Confirmation requise",
        ["general.adaptive_style"] = "Style adaptatif",
        ["general.unknown_raid"] = "raid-inconnu",
        ["billing.notification.debt_added_title"] = "Facture Vanguard créée",
        ["billing.notification.debt_added_message"] = "Dette différée ajoutée · {0}",
    };

    // Test/diagnostic seam. Production leaves this null and reads EFT's current locale.
    internal static Func<string?>? LocaleCodeOverride { get; set; }

    public static VanguardPresentationLanguage CurrentLanguage =>
        IsFrenchLocale(ResolveLocaleCode()) ? VanguardPresentationLanguage.French : VanguardPresentationLanguage.English;

    public static string Get(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return string.Empty;
        }

        IReadOnlyDictionary<string, string> primary = CurrentLanguage == VanguardPresentationLanguage.French
            ? FrenchValues
            : EnglishValues;

        if (primary.TryGetValue(key, out string? localized))
        {
            return localized;
        }

        // English is the canonical fallback for every locale and for missing French entries.
        return EnglishValues.TryGetValue(key, out string? fallback) ? fallback : key;
    }

    public static string GetOrDefault(string key, string fallback)
    {
        string value = Get(key);
        return string.Equals(value, key, StringComparison.Ordinal) ? fallback : value;
    }

    public static string Format(string key, params object?[] args)
    {
        return string.Format(CultureInfo.InvariantCulture, Get(key), args);
    }

    internal static bool HasCatalogKey(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return false;
        }

        return EnglishValues.ContainsKey(key) && FrenchValues.ContainsKey(key);
    }

    internal static bool HasCatalogParity(out string details)
    {
        List<string> issues = new();

        foreach (string key in EnglishValues.Keys)
        {
            if (!FrenchValues.ContainsKey(key))
            {
                issues.Add($"missing-fr:{key}");
            }
        }

        foreach (string key in FrenchValues.Keys)
        {
            if (!EnglishValues.ContainsKey(key))
            {
                issues.Add($"missing-en:{key}");
            }
        }

        details = issues.Count == 0 ? "OK" : string.Join(",", issues);
        return issues.Count == 0;
    }

    private static bool IsFrenchLocale(string? localeCode)
    {
        return string.Equals(localeCode?.Trim(), FrenchLocaleCode, StringComparison.OrdinalIgnoreCase);
    }

    private static string? ResolveLocaleCode()
    {
        try
        {
            if (LocaleCodeOverride is not null)
            {
                return LocaleCodeOverride();
            }

            // Keep the localization layer buildable under both net9.0 tooling and the
            // netstandard2.1 SPT client target. Assembly-CSharp is resolved only at runtime.
            Type? localeManagerType = Type.GetType("LocaleManagerClass, Assembly-CSharp", throwOnError: false);
            PropertyInfo? singletonProperty = localeManagerType?.GetProperty(
                "LocaleManagerClass",
                BindingFlags.Public | BindingFlags.Static);
            object? localeManager = singletonProperty?.GetValue(null);
            PropertyInfo? localeProperty = localeManagerType?.GetProperty(
                "String_0",
                BindingFlags.Public | BindingFlags.Instance);

            return localeProperty?.GetValue(localeManager) as string;
        }
        catch
        {
            // Localization must never prevent Vanguard UI from rendering.
            return null;
        }
    }
}
