using SPTarkov.Server.Core.Models.Utils;

// Responsibility: Defines request payloads accepted by the server runtime-audit settings.
// Flow: Caller input is deserialized into these data-only shapes, then validated and executed by the owning route/service.
// Authority boundary: Transport contract only; it does not authorize, persist, or execute the requested operation.
// Invariant: Payload defaults remain backward-compatible and contain no hidden side effects.
namespace Vanguard.Server.Operators.Audit.Requests;

// runtime-audit subsystem: audit config DTOs follow the same SPT route contract as
// Validated Vanguard POST routes: explicit IRequestData records.
public sealed record VanguardOperatorRuntimeAuditSettingsRequest(
    string? OwnerProfileId = null,
    string AuditLevel = "Operational",
    string CombatDiagnosticsScope = "Off",
    string PerformanceTelemetry = "SlowCallsOnly",
    bool DetailedDiagnosticPayloads = false,
    bool Enabled = false,
    bool MovementProbeEnabled = true,
    bool BrainProbeEnabled = true,
    bool SainProbeEnabled = true,
    bool LootingBotsProbeEnabled = true,
    bool OrbitProbeEnabled = true,
    bool SummaryLogEnabled = true,
    bool DecisionSnapshotLogEnabled = true,
    bool IntentDryRunEnabled = true,
    bool ThreatScannerDryRunEnabled = true,
    bool FirstActiveMobileMedicalLeaseEnabled = true,
    bool OperatorPostRaidPersistenceEnabled = true,
    bool HeadlessKeepGcEnabledInRaid = false,
    bool VerboseTransitionLogEnabled = false,
    float SnapshotIntervalSeconds = 1.0f,
    float SummaryIntervalSeconds = 60.0f,
    float TransitionLogMinIntervalSeconds = 2.0f,
    float ThreatScannerIntervalSeconds = 1.0f,
    bool MovementOutsideBubbleRecallEnabled = true,
    bool MovementSainBoundaryReturnEnabled = true,
    bool MovementSuppressExternalDuringRecallEnabled = true,
    bool MovementVerboseDoctrineLogEnabled = false,
    bool MovementTacticalRepositionEnabled = true,
    float MovementTacticalRepositionCooldownSeconds = 8.0f,
    float MovementTacticalRepositionMinDeltaMeters = 7.0f,
    float MovementTacticalBubbleMeters = 75.0f,
    float MovementSoftCorrectionMeters = 80.0f,
    float MovementHardCorrectionMeters = 88.0f,
    float MovementCombatCohesionForcedCatchupMeters = 32.0f,
    float MovementTravelCatchUpEnterMeters = 28.0f,
    float MovementTravelCatchUpExitMeters = 22.0f,
    float MovementTravelModeDwellSeconds = 1.25f,
    float MovementActionRallyClearMeters = 38.0f,
    float MovementActionRallyAcceptMeters = 45.0f,
    float MovementActionRallyPreferredMeters = 24.0f,
    float MovementLeaseStartCooldownSeconds = 10.0f,
    float MovementLeaseFailureCooldownSeconds = 12.0f,
    float MovementLeaseNoProgressSeconds = 7.0f,
    float MovementLeaseMaxDurationSeconds = 45.0f,
    int MovementActionRallyMaxReanchors = 2,
    bool MovementOpportunisticLootBrokerEnabled = true,
    float MovementOpportunisticLootMaxDistanceMeters = 38.0f,
    float MovementOpportunisticLootScanCooldownSeconds = 18.0f,
    float MovementOpportunisticLootGrantSeconds = 8.0f,
    bool LootOperationalSessionEnabled = true,
    bool LootBackupLongWeaponEnabled = true,
    bool LootBackupPistolEnabled = true,
    bool LootMedicalItemsEnabled = true,
    bool LootCompatibleMagazinesEnabled = true,
    bool LootCompatibleLooseAmmunitionEnabled = true,
    bool LootGrenadesEnabled = true,
    int LootMaximumTransactionsPerCorpse = 8,
    float LootMaximumSessionSeconds = 10.0f,
    int LootMaximumMedicalItemsPerSession = 4,
    int LootMaximumMagazinesPerSession = 4,
    int LootMaximumLooseAmmunitionRoundsPerSession = 180,
    int LootMaximumWeaponsPerSession = 1,
    string? UpdatedByProfileId = null,
    string? UpdatedBySource = null,
    string? Source = null,
    string? ClientBuild = null,
    string? ClientLabel = null,
    bool RequesterIsFikaInstalled = false,
    bool RequesterIsActualHeadlessProcess = false,
    bool RequesterIsHeadlessRequester = false,
    bool RequesterIsHost = false,
    bool RequesterRaidHostedByHeadless = false) : IRequestData;

public sealed record VanguardOperatorRuntimeAuditSettingsGetRequest(
    string? OwnerProfileId = null,
    string? Source = null,
    string? ClientBuild = null,
    string? ClientLabel = null,
    bool RequesterIsFikaInstalled = false,
    bool RequesterIsActualHeadlessProcess = false,
    bool RequesterIsHeadlessRequester = false,
    bool RequesterIsHost = false,
    bool RequesterRaidHostedByHeadless = false) : IRequestData;
